Dialog and movieform
bcvitanusic/ReactJS-Global-Mentoring-Program pull request #4
Opened 2023-04-12 18:53 UTC by bcvitanusic

2023-04-17 10:20 UTC, leandrocunha requested changes

2023-04-17 10:20 UTC, leandrocunha commented on glomentorprogram/src/components/Dialog/Dialog.js
> +const Dialog = ({ onClose, title, children }) => {
@bcvitanusic your implementation looks great but I'm curious to understand something. You put the children in a conditional statement, so if it has children put it, if not render a close button with Header? So if the Dialog need to show the content, will not have a close button and header?

what about putting the children together with a close, and header, and if there is no children, render nothing? Does it make sense?

2023-04-17 10:20 UTC, leandrocunha commented on glomentorprogram/src/components/Dialog/Dialog.stories.js
> +				<Dialog title={'Are you sure you want to delete movie?'} />
@bcvitanusic This implementation will not display your title, it's related to my comment in the `Dialog.js`

2023-04-17 10:20 UTC, leandrocunha commented on glomentorprogram/src/components/Dialog/Dialog.stories.js
> +				{' '}
@bcvitanusic you can remove the empty space

2023-04-17 11:43 UTC, bcvitanusic commented on glomentorprogram/src/components/Dialog/Dialog.js
> +const Dialog = ({ onClose, title, children }) => {
Yes, fixed.

2023-04-18 18:24 UTC, leandrocunha commented on glomentorprogram/src/components/Dialog/Dialog.stories.js
> +		baxkgrounds: {
@bcvitanusic the parameter `baxkgrounds` is correct, or did make a typo ?

2023-04-18 18:25 UTC, leandrocunha approved these changes

2023-04-19 16:05 UTC, merged